In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_50 = np.linspace(1,10)
sample_50[:10]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388,
       1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122])

In [3]:
series_1 = pd.Series(sample_50)
print(series_1.head())

0    1.000000
1    1.183673
2    1.367347
3    1.551020
4    1.734694
dtype: float64


In [4]:
samples = np.linspace(1,10,5)
samples

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
series_1 = pd.Series(samples)
series_1

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [6]:
print(series_1)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64


In [7]:
random = np.random.rand(10)
random

array([0.51658359, 0.85639937, 0.36636446, 0.51914646, 0.86025313,
       0.96408908, 0.29263058, 0.04165331, 0.08439604, 0.04333471])

In [8]:
ser_2 = pd.Series(random)
print(ser_2)

0    0.516584
1    0.856399
2    0.366364
3    0.519146
4    0.860253
5    0.964089
6    0.292631
7    0.041653
8    0.084396
9    0.043335
dtype: float64


In [9]:
#creating a series using list of elements 

In [10]:
list_elements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#step 2 pass it the Series Constructor to create a series

In [11]:
ser_3 = pd.Series(list_elements)
ser_3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [12]:
# for the data given below get the index and values after forming a series object
# step1 import the pandas
# step 2 create a pandas series using the data given
# data = {"India":"New Delhi","Japan":"Tokoyo","UK",'London'}

In [13]:
import pandas as pd
list_elements = [1,2,3,4,5,6,7,8,9,10]

In [14]:
ser_3 = pd.Series(list_elements)
ser_3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [15]:
# For the data given below,get the index and values after forming a Series object

In [16]:
Data = {"India":"New Delhi","Japan":"Tokyo","UK":"London"}
ser_data = pd.Series(Data)
ser_data

India    New Delhi
Japan        Tokyo
UK          London
dtype: object

In [17]:
ser_data.index

Index(['India', 'Japan', 'UK'], dtype='object')

In [18]:
ser_data.values

array(['New Delhi', 'Tokyo', 'London'], dtype=object)

In [19]:
# Create a Series using a range of 10 values and specify the index explicitly. Use capital alphabets to index explicitly

In [20]:
values = np.arange(10)
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
index_values = ['A','B','C','D','E','F','G','H','I','J']

In [22]:
ser_explicit_index = pd.Series(values, index=index_values)
ser_explicit_index

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int32

In [23]:
# Lets apply 'shape' and 'size' attributes for the series created in Exercise_4

In [24]:
ser_explicit_index.shape

(10,)

In [25]:
ser_explicit_index.size

10

In [26]:
# Slice the values of Series created for Exercise 4
#- (a) Slice from 4th Index upto the end with step size 3
#- (b) Slice the entire Series in reverse order
#- (c) Slice the entire Series with step Size 2

In [27]:
ser_explicit_index[4::3]

E    4
H    7
dtype: int32

In [28]:
ser_explicit_index[::-1]

J    9
I    8
H    7
G    6
F    5
E    4
D    3
C    2
B    1
A    0
dtype: int32

In [29]:
ser_explicit_index[::2]

A    0
C    2
E    4
G    6
I    8
dtype: int32

In [30]:
ser_explicit_index[::1]

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int32

In [31]:
# Convert the Series object values created for the exercise4 back into the list of values

In [32]:
print(type(ser_explicit_index))

<class 'pandas.core.series.Series'>


In [33]:
print(type(ser_explicit_index.tolist()))

<class 'list'>


In [34]:
# for the data given below, Construct a series and add data=[500,600,700]to the existing Series

In [35]:
# Step 1: construct the Series using Data given
# data = ['25','50','100','200','300','400']
# data_to_add = [500,600,700]

In [36]:
data = ['25','50','100','200','300','400']
data_to_add = [500,600,700]

In [37]:
series_before = pd.Series(data)
series_before

0     25
1     50
2    100
3    200
4    300
5    400
dtype: object

In [38]:
# Step 2: Construct the another Series usng 'data_to_add'

In [39]:
series_toAppend = pd.Series(data_to_add)
series_toAppend

0    500
1    600
2    700
dtype: int64

In [40]:
series_after = series_before.append(series_toAppend)
series_after

0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: object

In [ ]:
# Step 2: First Convert the created   Series with the string values to numeric using 'pd.to_numeric'method which
# converts the given Series with string values to series with numeric values

In [ ]:
# You can easily check out the docstring of 'to_numeric' method on pandas object by urself

In [41]:
new_series = pd.to_numeric(series_after)
new_series

0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: int64

In [ ]:
# step 3: Apply the condition to the numeric series created just now using indexing method inside the[]

In [42]:
cond = (new_series >= 100)

In [43]:
new_sorted = new_series[cond]
new_sorted

2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: int64

In [ ]:
# For data given below construct a Pandas DataFrame Object using blabels data to set the index of the Dataframe.
# After creating teh df display the summary of the basic information

In [46]:
# Step 1: Create a DataFrame object using the Data provided
----
exam_data = {'name':['Arun','Rama','Kantiana','James','Emily','Michael','Mathew','Laura','Kevin','Jones'],'score':[12,10,17,np.nan,9,30,15,np.nan,8,19],
              'attempts': [1,3,2,3,2,3,1,1,2,1],
                'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']}

labels = ['a','b','c','d','e','f','g','h','i','j']

SyntaxError: invalid syntax (<ipython-input-46-967761f29400>, line 2)

In [47]:
exam_data = {'name':['Arun','Rama','Kantiana','James','Emily','Michael','Mathew','Laura','Kevin','Jones'],'score':[12,10,17,np.nan,9,30,15,np.nan,8,19],
              'attempts': [1,3,2,3,2,3,1,1,2,1],
                'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']}

labels = ['a','b','c','d','e','f','g','h','i','j']

In [48]:
exam_df = pd.DataFrame(exam_data,index=labels)
exam_df

name  score  attempts qualify
a      Arun   12.0         1     yes
b      Rama   10.0         3      no
c  Kantiana   17.0         2     yes
d     James    NaN         3      no
e     Emily    9.0         2      no
f   Michael   30.0         3     yes
g    Mathew   15.0         1     yes
h     Laura    NaN         1      no
i     Kevin    8.0         2      no
j     Jones   19.0         1     yes

In [ ]:
#Step 2: Display the Basic