In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_50 = np.linspace(1,10)
sample_50[:10]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388,
       1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122])

In [3]:
series_1 = pd.Series(sample_50)
print(series_1.head())

0    1.000000
1    1.183673
2    1.367347
3    1.551020
4    1.734694
dtype: float64


In [4]:
samples = np.linspace(1,10,5)
samples

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
series_1 = pd.Series(samples)
series_1

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [6]:
print(series_1)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64


In [7]:
random = np.random.rand(10)
random

array([0.34682536, 0.60212285, 0.31234869, 0.34050648, 0.47836198,
       0.14455027, 0.73159978, 0.78298408, 0.60599007, 0.13701087])

In [8]:
ser_2 = pd.Series(random)
print(ser_2)

0    0.346825
1    0.602123
2    0.312349
3    0.340506
4    0.478362
5    0.144550
6    0.731600
7    0.782984
8    0.605990
9    0.137011
dtype: float64


In [9]:
#creating a series using list of elements 

In [10]:
list_elements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#step 2 pass it the Series Constructor to create a series

In [11]:
ser_3 = pd.Series(list_elements)
ser_3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [12]:
# for the data given below get the index and values after forming a series object
# step1 import the pandas
# step 2 create a pandas series using the data given
# data = {"India":"New Delhi","Japan":"Tokoyo","UK",'London'}

In [13]:
import pandas as pd
list_elements = [1,2,3,4,5,6,7,8,9,10]

In [15]:
ser_3 = pd.Series(list_elements)
ser_3

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
# For the data given below,get the index and values after forming a Series object

In [17]:
Data = {"India":"New Delhi","Japan":"Tokyo","UK":"London"}
ser_data = pd.Series(Data)
ser_data

India    New Delhi
Japan        Tokyo
UK          London
dtype: object

In [18]:
ser_data.index

Index(['India', 'Japan', 'UK'], dtype='object')

In [19]:
ser_data.values

array(['New Delhi', 'Tokyo', 'London'], dtype=object)

In [20]:
# Create a Series using a range of 10 values and specify the index explicitly. Use capital alphabets to index explicitly

In [21]:
values = np.arange(10)
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
index_values = ['A','B','C','D','E','F','G','H','I','J']

In [24]:
ser_explicit_index = pd.Series(values, index=index_values)
ser_explicit_index

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int32

In [ ]:
# Lets apply 'shape' and 'size' attributes for the series created in Exercise_4

In [25]:
ser_explicit_index.shape

(10,)

In [26]:
ser_explicit_index.size

10

In [ ]:
# Slice the values of Series created for Exercise 4
#- (a) Slice from 4th Index upto the end with step size 3
#- (b) Slice the entire Series in reverse order
#- (c) Slice the entire Series with step Size 2

In [27]:
ser_explicit_index[4::3]

E    4
H    7
dtype: int32

In [28]:
ser_explicit_index[::-1]

J    9
I    8
H    7
G    6
F    5
E    4
D    3
C    2
B    1
A    0
dtype: int32

In [31]:
ser_explicit_index[::2]

A    0
C    2
E    4
G    6
I    8
dtype: int32

In [38]:
ser_explicit_index[::1]

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int32

In [ ]:
# Convert the Series object values created for the exercise4 back into the list of values

In [39]:
print(type(ser_explicit_index))

<class 'pandas.core.series.Series'>


In [44]:
print(type(ser_explicit_index.tolist()))

<class 'list'>


In [ ]:
# for the data given below, Construct a series and add data=[500,600,700]to the existing Series

In [ ]:
# Step 1: construct the Series using Data given
# data = ['25','50','100','200','300','400']
# data_to_add = [500,600,700]

In [48]:
data = ['25','50','100','200','300','400']
data_to_add = [500,600,700]

In [51]:
series_before = pd.Series(data)
series_before

0     25
1     50
2    100
3    200
4    300
5    400
dtype: object

In [46]:
# Step 2: Construct the another Series usng 'data_to_add'

In [49]:
series_toAppend = pd.Series(data_to_add)
series_toAppend

0    500
1    600
2    700
dtype: int64

In [52]:
series_after = series_before.append(series_toAppend)
series_after

0     25
1     50
2    100
3    200
4    300
5    400
0    500
1    600
2    700
dtype: object