<a href="https://colab.research.google.com/github/rishabrath31/PythonClass/blob/main/PythonclassP14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
 
arr = np.array([[0, 1, 4, 2, 3],
                [4, 2, 0, 1, 5],
                [2, 2, 1, 0, 3],
                [3, 4, 5, 3, 0]])
print(arr)

[[0 1 4 2 3]
 [4 2 0 1 5]
 [2 2 1 0 3]
 [3 4 5 3 0]]


In [5]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
   
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]
